import type { ReactNode } from 'react';
import {
  HomeOutlined,
  DashboardOutlined,
  ApartmentOutlined,
  AlertOutlined,
  BankOutlined,
  FileProtectOutlined,
  ShopOutlined,
  DeploymentUnitOutlined,
  FileTextOutlined,
  FileWordOutlined,
  AccountBookOutlined,
  PayCircleOutlined,
  PhoneOutlined,
  ToolOutlined,
  ScheduleOutlined,
  RocketOutlined,
  AuditOutlined,
  BellOutlined,
  ClusterOutlined,
  CopyrightOutlined,
  TeamOutlined,
  SettingOutlined,
  SafetyOutlined,
  RobotOutlined,
  CloudUploadOutlined,
  BarChartOutlined,
  FundOutlined,
  ProjectOutlined,
  IdcardOutlined,
  SwapOutlined,
  FormOutlined,
  NotificationOutlined,
  UserOutlined,
  ExportOutlined,
  FieldTimeOutlined,
  HomeFilled,
  ThunderboltOutlined,
  FileSearchOutlined,
  TransactionOutlined,
  ReconciliationOutlined,
  PercentageOutlined,
  DollarOutlined,
  RollbackOutlined,
  SolutionOutlined,
  BuildOutlined,
  CarryOutOutlined,
  MessageOutlined,
  AppstoreOutlined,
  ControlOutlined,
  MenuOutlined,
  ExperimentOutlined,
  SyncOutlined,
  EnvironmentOutlined,
  LogoutOutlined,
  CalendarOutlined,
} from '@ant-design/icons';

/** 按路由 path 映射菜单/页签/标题图标 */
export const PATH_ICONS: Record<string, ReactNode> = {
  '/': <HomeOutlined />,
  '/dashboard': <DashboardOutlined />,
  '/ops-calendar': <CalendarOutlined />,
  '/dashboard/consolidate': <FundOutlined />,
  '/business-plans': <BarChartOutlined />,
  '/alerts/rules': <ControlOutlined />,
  '/alerts/records': <AlertOutlined />,
  '/projects': <ProjectOutlined />,
  '/assets': <BankOutlined />,
  '/certificates': <FileProtectOutlined />,
  '/mortgages': <IdcardOutlined />,
  '/asset-transfers': <SwapOutlined />,
  '/evaluations': <FormOutlined />,
  '/lease-listings': <ShopOutlined />,
  '/tender/announcements': <NotificationOutlined />,
  '/tenants': <UserOutlined />,
  '/disposals': <ExportOutlined />,
  '/occupations': <FieldTimeOutlined />,
  '/self-uses': <HomeFilled />,
  '/contracts': <FileTextOutlined />,
  '/contract-templates': <FileWordOutlined />,
  '/vacate-orders': <LogoutOutlined />,
  '/billing/bills': <AccountBookOutlined />,
  '/meters': <DashboardOutlined />,
  '/apportion-configs': <PercentageOutlined />,
  '/payments': <PayCircleOutlined />,
  '/payments/pending-confirm': <PayCircleOutlined />,
  '/refunds': <RollbackOutlined />,
  '/adjustments/fee-reliefs': <AccountBookOutlined />,
  '/adjustments/rent-adjusts': <AccountBookOutlined />,
  '/invoices': <ReconciliationOutlined />,
  '/invoice-tax-rates': <PercentageOutlined />,
  '/finance/bank-flows': <TransactionOutlined />,
  '/finance/vouchers': <SolutionOutlined />,
  '/dunning/auto': <PhoneOutlined />,
  '/dunning/records': <PhoneOutlined />,
  '/repairs': <ToolOutlined />,
  '/vendors': <BuildOutlined />,
  '/inspections': <FileSearchOutlined />,
  '/tasks': <CarryOutOutlined />,
  '/approvals': <AuditOutlined />,
  '/revitalization': <RocketOutlined />,
  '/asset-audits': <FileSearchOutlined />,
  '/asset-map': <EnvironmentOutlined />,
  '/reports': <BarChartOutlined />,
  '/regulation/reports': <AuditOutlined />,
  '/notifications': <BellOutlined />,
  '/fixed-assets': <ClusterOutlined />,
  '/intangible-assets': <CopyrightOutlined />,
  '/org/companies': <ApartmentOutlined />,
  '/org/departments': <TeamOutlined />,
  '/system/users': <UserOutlined />,
  '/config/versions': <SettingOutlined />,
  '/system/roles': <SafetyOutlined />,
  '/system/menus': <MenuOutlined />,
  '/intelligence/templates': <ExperimentOutlined />,
  '/intelligence/sessions': <RobotOutlined />,
  '/intelligence/reports': <FileTextOutlined />,
  '/migrations/batches': <CloudUploadOutlined />,
};

export const GROUP_ICONS: Record<string, ReactNode> = {
  工作台: <AppstoreOutlined />,
  协同管控: <AlertOutlined />,
  招租与合同: <FileTextOutlined />,
  收费财务: <DollarOutlined />,
  资产档案: <BankOutlined />,
  现场运维: <ToolOutlined />,
  智能中心: <RobotOutlined />,
  系统设置: <SettingOutlined />,
};

export function getPathIcon(path: string): ReactNode {
  return PATH_ICONS[path] ?? <AppstoreOutlined />;
}

export function getGroupIcon(title: string): ReactNode {
  return GROUP_ICONS[title] ?? <AppstoreOutlined />;
}

/** 看板指标图标 */
export const DASHBOARD_ICONS: Record<string, ReactNode> = {
  资产总数: <BankOutlined />,
  在租宗数: <ShopOutlined />,
  空置宗数: <HomeOutlined />,
  '空置面积 (㎡)': <EnvironmentOutlined />,
  出租率: <FundOutlined />,
  收缴率: <PayCircleOutlined />,
  '应收 (元)': <AccountBookOutlined />,
  '实收 (元)': <DollarOutlined />,
  '欠费 (元)': <AlertOutlined />,
  合同总数: <FileTextOutlined />,
  集团资产总数: <ApartmentOutlined />,
  集团出租率: <FundOutlined />,
  '集团空置面积 (㎡)': <EnvironmentOutlined />,
};
