apiVersion: v1
kind: Service
metadata:
  name: ams-api
  namespace: ams
  labels:
    app.kubernetes.io/name: ams-api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: ams-api
  ports:
    - name: http
      port: 80
      targetPort: http
