-- ============================================================================
-- 审计列补齐：所有 extends BaseEntity 的实体对应表必须含
-- created_at / updated_at / created_by / updated_by 四列。
-- 使用 IF NOT EXISTS 保证幂等，不覆盖已有列定义。
-- ============================================================================

ALTER TABLE company          ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE department       ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE "user"           ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE role             ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE project          ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE asset            ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE asset_transfer   ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE tenant           ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE contract         ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE vacate_order     ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE payment_plan     ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE bill             ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE payment          ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE prepay           ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE refund_order     ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE invoice          ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE repair_order     ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE alert_rule       ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE task             ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE disposal_order   ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE occupation_order ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE self_use_order   ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE evaluation_request ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE revitalization_task ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
ALTER TABLE business_plan    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ, ADD COLUMN IF NOT EXISTS created_by BIGINT, ADD COLUMN IF NOT EXISTS updated_by BIGINT;
