-- 空置 KPI / 水电单价 / 资产坐标

ALTER TABLE asset ADD COLUMN IF NOT EXISTS vacant_reason VARCHAR(50);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS vacant_since TIMESTAMPTZ;
ALTER TABLE asset ADD COLUMN IF NOT EXISTS longitude NUMERIC(10,7);
ALTER TABLE asset ADD COLUMN IF NOT EXISTS latitude NUMERIC(10,7);

ALTER TABLE apportion_config ADD COLUMN IF NOT EXISTS unit_price_water NUMERIC(18,4) DEFAULT 3.5;
ALTER TABLE apportion_config ADD COLUMN IF NOT EXISTS unit_price_electric NUMERIC(18,4) DEFAULT 0.8;
ALTER TABLE apportion_config ADD COLUMN IF NOT EXISTS unit_price_gas NUMERIC(18,4) DEFAULT 2.5;
ALTER TABLE apportion_config ADD COLUMN IF NOT EXISTS minimum_usage NUMERIC(18,2) DEFAULT 0;
